<div class="container-wrap"><div class="content-top-wrap"><div><ul class="location-list"><li>HOME</li><li>상품</li><li>상품 분류 관리</li><li>전시 카테고리 관리</li></ul><h2> 전시 카테고리 관리 </h2></div><div><div data-v-7cf0eadb="" class="content-top" style="display: none;"><div data-v-7cf0eadb="" class="shop-mall-list-wrap"><div data-v-7cf0eadb="" class="mall-tab-list" style="padding: 0px 0px 0px 50px;"><button data-v-7cf0eadb="" class="btn-list-all"></button><div data-v-7cf0eadb="" class="sb_cover-for-ul slick-initialized slick-slider"><div class="slick-list"><div class="slick-track" style="opacity: 1; width: 0px; transform: translate3d(0px, 0px, 0px);"><div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 0px;"><div><div data-v-7cf0eadb="" class="slide-item" style="width: 100%; display: inline-block;"><a data-v-7cf0eadb="" href="/pro/product/categorization/display?mallNo=56042" class="on" tabindex="0"> dojang </a></div></div></div></div></div></div><!----></div><div data-v-7cf0eadb="" class="mall-list-all"><ul data-v-7cf0eadb=""><li data-v-7cf0eadb=""><a data-v-7cf0eadb="" href="/pro/product/categorization/display?mallNo=56042" class=""><span data-v-7cf0eadb=""> dojang </span></a></li></ul></div></div></div></div></div><div class="content-bottom-wrap"><div class="contents" tooltip-option="[object Object]"><div class="box-view-wrap"><div class="view-title"> 전시카테고리 설정 <div class="btn-right"><button type="button" class="excelBtn"><span class="sp_ico excel"></span>엑셀 다운로드 </button></div></div><div class="box-cont type-4"><div class="settings_item_bx"><div class="set-cont-bx" style="overflow: hidden;"><div data-v-5845fb09="" class="tree_wrap arcodion_wrap"><div data-v-5845fb09="" class="tree_head arcodion_top type-all"><div class="btn_wrap_left"><button type="button" class="treeBtn type-plus"><span>1차 카테고리 추가</span></button><button type="button" class="treeBtn type-minus"><span>삭제</span></button></div><div class="btn_wrap_right"><button type="button" class="all-folder type-open"><span>전체 열기</span></button><button type="button" class="all-folder type-close"><span>전체 닫기</span></button></div></div><div data-v-5845fb09="" class="treeWrap arcodion"><div data-v-5845fb09="" class="arcodion_lst"><div data-v-32ce4ed6="" data-v-5845fb09="" style="user-select: none;"><div data-v-32ce4ed6="" id="tree" class="tui-tree-wrap"><ul class="tui-tree tui-tree-root"><li id="tui-tree-node-4424" class="tui-tree-node tui-tree-leaf tui-tree-selected">
		<div data-product-count="3" class="tui-tree-content-wrapper">
			<span class="tui-tree-text tui-js-tree-text">
				<span class="tui-tree-ico tui-ico-file-line"></span>
				<span class="tui-tree-ico tui-ico-file"></span>
				<span class="tui-node-name">예시 카테고리</span>
				<span class="ico_noshow display-node-Y"></span>


			</span>
		</div>
	</li></ul><span class="tui-tree-drop" style="position: absolute; display: none;"></span><div class="tui-tree-line" style="position: absolute; display: none;"></div></div><!----></div></div></div></div><div class="arcodion_detail"><div class="notice-box" style="margin-top: 0px;"><ul><li> 전시카테고리 설정은 최종적으로 [변경사항 저장] 버튼을 클릭 후 반영됩니다. </li><li> 변경사항을 저장하지 않고 다른 메뉴로 이동 시 설정한 내용은 반영되지 않으니 반드시 저장하시길 바랍니다. </li><li> 카테고리 엑셀 일괄등록은 신규 등록만 가능하며, 카테고리 일괄 수정/삭제 기능은 제공하지 않습니다. </li><li> 일괄등록 샘플 다운로드에 제공되는 가이드를 참고하여 입력 후 엑셀 일괄 등록하시길 바랍니다. </li><li> 엑셀 다운로드 시 전체 카테고리를 다운로드 할 수 있습니다. </li></ul></div><div class="box-cont"><table class="ncp_tbl"><colgroup><col style="width: 200px;"><col></colgroup><tbody><tr><th>카테고리 번호</th><td id="displayCategoryNo"> 242712 </td></tr><tr><th>카테고리 URL</th><td id="displayCategoryUrl"><button class="double_click_allow"> 주소복사 </button></td></tr><tr><th><label>카테고리명</label></th><td><div data-v-74e08c01="" class="input-vue-container count_target"><div data-v-74e08c01="" class="inputbox-wrap"><input data-v-74e08c01="" type="text" name="displayCategoryName" maxlength="30" placeholder="" autocomplete="false" class="type-2" style="width: 200px; text-align: left;"><span data-v-74e08c01="" class="count_wrap"><span data-v-74e08c01="" class="count">7</span>/30</span><!----><!----></div> <!----></div></td></tr><tr><th>노출여부</th><td id="displayYn"><div class="inputbox_wrap"><span class="radio_wrap"><input type="radio" id="category-show-radio" name="displayYnOption" value="Y"><label for="category-show-radio">노출함</label><input type="radio" id="category-hide-radio" name="displayYnOption" value="N"><label for="category-hide-radio">노출 안 함</label></span></div></td></tr><tr><th>등록된 상품 수</th><td>3개</td></tr></tbody></table></div></div></div></div></div></div></div><div><div id="notice-popup" class="alarm-popup-remote" style="display: block; z-index: 20;"><div data-v-0908c380=""><!----><!----></div><a href="#top" class="up">위로 이동</a><a href="#bottom" class="down">밑으로 이동</a></div></div><div class="copy-wrap"><p>© NHN COMMERCE : Corp All Rights Reserved</p></div></div></div>
